remote_theme: benbalter/retlab
title: StuckOverflow's Website
description: A website for "Trends on Tags"'s data story
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
